---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: server
  namespace: metallb-system
spec:
  addresses:
  - 10.0.10.50-10.0.10.99
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: server
  namespace: metallb-system
spec:
  ipAddressPools:
  - server
