---
apiVersion: v1
kind: Namespace
metadata:
  name: yeetcode

# TODO: Use 1Password to populate the value for this secret.
---
apiVersion: v1
kind: Secret
metadata:
  name: yeetcode
  namespace: yeetcode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeetcode
  namespace: yeetcode
  labels:
    app: yeetcode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yeetcode
  template:
    metadata:
      labels:
        app: yeetcode
    spec:
      containers:
      - name: yeetcode
        image: ghcr.io/sudomateo/yeetcode:latest
        ports:
          - containerPort: 3000
            name: http
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: yeetcode
              key: discord-token
        - name: DISCORD_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: yeetcode
              key: discord-public-key
---
apiVersion: v1
kind: Service
metadata:
  name: yeetcode
  namespace: yeetcode
spec:
  selector:
    app: yeetcode
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
